name: E2ETests  # Changed to match KuCoin naming

on:
  push:
  pull_request:  # Added pull_request trigger
  workflow_dispatch:  # Added manual trigger option

jobs:
  E2ETests:  # Changed job ID to match KuCoin
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Test Public Read API Calls  
        run: npm run test -- public.read.test.ts

      - name: Test Private Read API Calls  
        run: npm run test -- private.read.test.ts

      - name: Test Private Write API Calls 
        run: npm run test -- private.write.test.ts

      - name: Test Public WS  
        run: npm run test -- public.ws.test.ts

        env:
          API_KEY_COM: ${{ secrets.API_KEY_COM }}
          API_SECRET_COM: ${{ secrets.API_SECRET_COM }}
          PROXY_ENABLED: ${{ secrets.PROXY_ENABLED }}
          PROXY_HOST: ${{ secrets.PROXY_HOST }}
          PROXY_PASS: ${{ secrets.PROXY_PASS }}
          PROXY_PORT: ${{ secrets.PROXY_PORT }}
          PROXY_USER: ${{ secrets.PROXY_USER }}
