name: E2ETests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PROXY_ENABLED: ${{ secrets.PROXY_ENABLED }}
  PROXY_HOST: ${{ secrets.PROXY_HOST }}
  PROXY_PASS: ${{ secrets.PROXY_PASS }}
  PROXY_PORT: ${{ secrets.PROXY_PORT }}
  PROXY_USER: ${{ secrets.PROXY_USER }}


jobs:
  E2ETests:
    name: 'Build & Test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Test Public Read API Calls
        run: npm run test -- public.read.test.ts

      - name: Test Public WS
        run: npm run test -- public.ws.test.ts

      - name: Test Private Read HMAC API Calls
        run: npm run test -- private.readHMAC.test.ts
        env:
          API_KEY_COM: ${{ secrets.API_KEY_COM }}
          API_SECRET_COM: ${{ secrets.API_SECRET_COM }}

      - name: Test Private Write HMAC API Calls
        run: npm run test -- private.writeHMAC.test.ts
        env:
          API_KEY_COM: ${{ secrets.API_KEY_COM }}
          API_SECRET_COM: ${{ secrets.API_SECRET_COM }}

      - name: Test Private Read RSA API Calls
        run: npm run test -- private.readRSA.test.ts
        env:
            API_KEY_COM_RSA: ${{ secrets.API_KEY_COM_RSA }}
            API_SECRET_COM_RSA: ${{ secrets.API_SECRET_COM_RSA }}
  
      - name: Test Private Write RSA API Calls
        run: npm run test -- private.writeRSA.test.ts
        env:
          API_KEY_COM_RSA: ${{ secrets.API_KEY_COM_RSA }}
          API_SECRET_COM_RSA: ${{ secrets.API_SECRET_COM_RSA }}


